model_opts:
  model: ATGC
  obs_input_type: [ped_head, ped_legs, scene_context]
  apply_class_weights: false
  normalize_boxes: true
  generator: True
net_opts:
  backbone: alexnet
exp_opts:
  datasets: [pie, jaad_all, jaad_beh]
  batch_size: [32, 32, 32]
  epochs: [20, 20, 20]
  lr: [0.000005, 0.000005, 0.000005]

