model_opts:
  model: CAPformer
  obs_input_type: [local_box, box]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: c3d
exp_opts:
  datasets: [pie, jaad_all, jaad_beh]
  batch_size: [8, 8, 8]
  epochs: [60, 20, 20]
  lr: [5.0e-5, 5.0e-05, 5.0e-05]
